# Generated by Django 3.1.2 on 2020-11-03 00:36

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('family', models.CharField(max_length=200, null=True)),
                ('continent', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('languages', models.ManyToManyField(to='master.Language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to=master.models.content_file_name)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.language')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to=master.models.content_file_name)),
                ('title', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(choices=[('Direct Input', 'Direct Input'), ('WikiTongues', 'WikiTongues'), ('LORELAD Input', 'LORELAD Input'), ('YouTube', 'YouTube'), ('Physical Recorder', 'Physical Recorder')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quality', models.IntegerField(null=True)),
                ('date_recorded', models.DateTimeField(null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.language')),
                ('speakerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.speaker')),
            ],
            options={
                'ordering': ['date_recorded'],
            },
        ),
    ]
