# Generated by Django 3.1.3 on 2020-11-23 02:00

from django.db import migrations, models
import django.db.models.deletion
import master.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('family', models.CharField(max_length=200, null=True)),
                ('continent', models.CharField(choices=[('as', 'Asia'), ('af', 'Africa'), ('oc', 'Oceania'), ('eu', 'Europe'), ('na', 'North America'), ('sa', 'South America'), ('nan', 'Not Defined')], default='nan', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('languages', models.ManyToManyField(to='master.Language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(default='4oSPG3sR', max_length=8, null=True, unique=True)),
                ('media', models.FileField(null=True, upload_to=master.models.content_file_name)),
                ('title', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(choices=[('Direct Input', 'Direct Input'), ('WikiTongues', 'WikiTongues'), ('LORELAD Input', 'LORELAD Input'), ('YouTube', 'YouTube'), ('Physical Recorder', 'Physical Recorder')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('quality', models.IntegerField(null=True)),
                ('date_recorded', models.DateTimeField(null=True)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.language')),
                ('speakerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.speaker')),
            ],
            options={
                'ordering': ['date_recorded'],
            },
        ),
    ]
