# Generated by Django 3.1.2 on 2020-11-23 03:38

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='num_recordings',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='num_speakers',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='summary',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='V9ylF3AU', max_length=8, null=True, unique=True),
        ),
    ]
