# Generated by Django 3.1.3 on 2020-12-02 22:43

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('master', '0002_auto_20201122_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='video',
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='language',
            name='continent',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='num_recordings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='num_speakers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='aVha1nIe', max_length=8, null=True, unique=True),
        ),
    ]
