# Generated by Django 3.1.3 on 2020-12-06 18:02

from django.db import migrations, models
import master.models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('master', '0004_auto_20201202_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='cov_image',
            field=models.ImageField(null=True, upload_to=master.models.image_folder),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='5MIc3z', max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
