# Generated by Django 3.1.3 on 2020-12-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_auto_20201206_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='speaker',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='HGfXo4', max_length=8, null=True, unique=True),
        ),
    ]
