# Generated by Django 3.1.3 on 2020-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20201211_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='tags',
        ),
        migrations.AddField(
            model_name='record',
            name='tag',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_id',
            field=models.CharField(default='MSgnaZ', max_length=8, null=True, unique=True),
        ),
    ]
