# Generated by Django 3.1.2 on 2020-10-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0004_auto_20201025_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='recordings/')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.language')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.speaker')),
            ],
        ),
    ]
