# Generated by Django 3.1.2 on 2020-11-02 18:50

import Recordings.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to=Recordings.models.content_file_name)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.language')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.speaker')),
            ],
        ),
    ]
