# Generated by Django 3.1.2 on 2020-11-02 01:10

import Recordings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to=Recordings.models.content_file_name),
        ),
    ]
