# Generated by Django 3.1.2 on 2020-10-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_auto_20201024_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
