# Generated by Django 3.1.2 on 2020-10-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_language_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='phone',
            new_name='continent',
        ),
        migrations.AddField(
            model_name='record',
            name='date_recorded',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='media',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='record',
            name='quality',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='source',
            field=models.CharField(choices=[('Direct Input', 'Direct Input'), ('WikiTongues', 'WikiTongues'), ('LORELAD Input', 'LORELAD Input'), ('YouTube', 'YouTube'), ('Physical Recorder', 'Physical Recorder')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='languages',
            field=models.ManyToManyField(to='languages.Language'),
        ),
    ]
